# Generated by Django 5.1.5 on 2025-09-11 13:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['category', 'location', 'name']},
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='category',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('ambulance', 'Ambulance'), ('police', 'Police'), ('fire', 'Fire Department'), ('hotline', 'Emergency Hotline'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 11, 13, 50, 46, 619202, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
