# Generated by Django 5.1.5 on 2025-09-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_delete_location_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('first_aid', 'First Aid'), ('cpr', 'CPR'), ('bleeding', 'Bleeding Control'), ('other', 'Other Medical Procedures')], default='other', max_length=100),
        ),
    ]
