# Generated by Django 5.1.5 on 2025-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_emergencycontact_options_and_more'),
        ('education', '0003_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_contacts',
            field=models.ManyToManyField(blank=True, related_name='related_articles', to='contacts.emergencycontact'),
        ),
    ]
